### ISSUE TITLE
CalcPAC

### ISSUE THREAD

**Issue by LELUSHU** [asoplata/propofol-coupling-2017-full#2]
we can't find CalcPAC.m in the code in /dynasim/ files. we  want to run the code in /fig8/ file, but matlab say it can't find CalcPAC.m. so we turn to you for help!!.  This is my email:270738270@qq.com.   Thanks!!!

**Comment by asoplata** [comment]
You're right, somehow I forgot the `CalcPAC.m` function. It has been added to `/dynasim/functions` where it belongs, so if you pull from the repo, it should work now. I will add, however, that we did NOT use it in the paper, even though it is in the Figure 8 code. There were issues with getting the filters accurate that led us to abandon its use, and we use different code now for our measure of PAC. In other words, I would not rely much on the plots that are produced by `CalcPAC`. Let me know if this fixes the problem.

**Comment by LELUSHU** [comment]
thanks！！your code has fixed the problem!!!
